### ISSUE TITLE
Remove react.txt and make it package data

### ISSUE THREAD

**Issue by jaredlander** [thepira/cv.glmmLasso#10]
http://r-pkgs.had.co.nz/data.html

**Comment by jaredlander** [comment]
```
reaction <- readr::read_tsv('inst/data/reaction.txt')
devtools::use_data(reaction)
```

**Comment by jaredlander** [comment]
This will require you to document the data as in http://r-pkgs.had.co.nz/data.html and allows you to load the data like `data(reaction, package='cv.glmmLasso')`

**Comment by thepira** [comment]
rda file already there, will commit
