### ISSUE TITLE
Failed to install this package.

### ISSUE THREAD

**Issue by yanfanevan** [thepira/cv.glmmLasso#14]
Hi, I tried to install this package, but always fail. could you please give some guide on that? infos are down below. Thank you!
`remotes::install_github("thepira/cv.glmmLasso")
Downloading GitHub repo thepira/cv.glmmLasso@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                          
2: CRAN packages only           
3: None                         
4: dismo (1.1-4 -> 1.3-2) [CRAN]

Enter one or more numbers, or an empty line to skip updates:3
✓  checking for file ‘/private/var/folders/cj/v2lhdtmx6b1_q3lh6vsxnppm0000gn/T/RtmppfjYhc/remotes66b730f07a65/thepira-cv.glmmLasso-dbe1c57/DESCRIPTION’ ...
─  preparing ‘cv.glmmLasso’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘cv.glmmLasso_0.0.0.9000.tar.gz’
   
* installing *source* package ‘cv.glmmLasso’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
Warning: file ‘soccer.rda’ has magic number 'versi'
  Use of save versions prior to 2 is deprecated
Error in load(zfile, envir = tmp_env) : 
  復原文件幻数出错(文件可能有损坏)-- 没有载入任何数据
ERROR: lazydata failed for package ‘cv.glmmLasso’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/cv.glmmLasso’
错误: Failed to install 'cv.glmmLasso' from GitHub:
  (由警告转换成)installation of package ‘/var/folders/cj/v2lhdtmx6b1_q3lh6vsxnppm0000gn/T//RtmppfjYhc/file66b77bf395fc/cv.glmmLasso_0.0.0.9000.tar.gz’ had non-zero exit status
`
My R version as follows. I also tried the new version of R(4.0.3), but still not working.
`> R.version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          6.3                         
year           2020                        
month          02                          
day            29                          
svn rev        77875                       
language       R                           
version.string R version 3.6.3 (2020-02-29)
nickname       Holding the Windsock  `

**Comment by yanfanevan** [comment]
sorry, this is my first time comment on Github, maybe some format is not correctly used.

**Comment by jaredlander** [comment]
First idea would be to update the `{dismo}` package by itself, restart then try to install this package. If that does not work it might just be the sample data causing issues and @thepira would have to rebuild that and push up here again.

**Comment by yanfanevan** [comment]
Thank you for your reply. I just tried it but unfortunately still not working.

**Comment by wdalehouston** [comment]
Same issue here. Have tried this on Linux on R 4.0.3 and up.

**Comment by jaredlander** [comment]
Is is still asking to update dismo?

**Comment by wdalehouston** [comment]
I updated dismo manually, and still get the following on 4.1.2 on CentOS 8. I have seen the same error on other systems. 

*** moving datasets to lazyload DB
Warning: file ‘soccer.rda’ has magic number 'versi'
  Use of save versions prior to 2 is deprecated
Error in load(zfile, envir = tmp_env) :
  bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: lazydata failed for package ‘cv.glmmLasso’

**Comment by mebrooks** [comment]
I also get this error, even after installing dismo and closing and reopening R 4.1.2 on macOS Monterey. 

Edit: I found a fork that does install
```
devtools::install_github("https://github.com/PayamEmami/cv.glmmLasso")
```

Edit again: It looks like multiple forks found the solution.

**Comment by jaredlander** [comment]
There was some issue with the soccer.rda file and #15 should have fixed it. Should be good now.

**Comment by alanbw** [comment]
Still having the same issues as described above by wdalehouston on 4.3.0 and Mac OS Big Sur.

**Comment by jaredlander** [comment]
@tknoch8 do you think the .rda needs to be rebuilt?

**Comment by mebrooks** [comment]
AFAICT, that data is redundant. Maybe you could try the pull request discussed [here](https://github.com/thepira/cv.glmmLasso/pull/18#issuecomment-1354420685)
`install_github("https://github.com/mebrooks/cv.glmmLasso")`

**Comment by jaredlander** [comment]
The data is used in the examples for the functions so we can't just remove it. We need to figure out the best way to keep it stored.

**Comment by mebrooks** [comment]
[This](https://github.com/thepira/cv.glmmLasso/pull/18/files#r1613413714) works for me `data("soccer", package = "glmmLasso")`. I explained it [here](https://github.com/thepira/cv.glmmLasso/pull/18#issuecomment-1354420685) but maybe you didn't see it because of the holiday season.

**Comment by alanbw** [comment]
Thanks for the help. I was able to install the package using the fork mentioned above by mebrooks.

**Comment by jaredlander** [comment]
This should be fixed again with #21

**Comment by mebrooks** [comment]
[CRAN says](https://cran.r-project.org/doc/FAQ/R-exts.html#The-DESCRIPTION-file) "Packages needed to use datasets from the package should be in ‘Imports’" and that is done in the `DESCRIPTION` file of `cv.glmmLasso` [here](https://github.com/thepira/cv.glmmLasso/blob/b8303693796c9d10f9456b9dc5e84f54b5a67408/DESCRIPTION#L11). That's why my suggested fix works as described [here](https://github.com/thepira/cv.glmmLasso/pull/18#discussion_r1613413714). 

Redundantly maintaining the data here could create more work or confusion in the future.

**Comment by tknoch8** [comment]
@mebrooks I will be submitting a pull request accomplishing this shortly.

**Comment by mebrooks** [comment]
@tknoch8, I don't understand what's wrong with my pull request #18. It has the added benefit of allowing multiple random intercepts whereas the current version only supports one. I have done extensive testing on my fork (forecast evaluation on 27 data sets with 15 horizon lengths, but only a single global model to regularize).
