### ISSUE TITLE
git-lfs smudge 'data/soccer.rda': git-lfs: command not found

### ISSUE THREAD

**Issue by mebrooks** [thepira/cv.glmmLasso#17]
I keep getting this error from the master branch since the latest commit (`git-lfs smudge 'data/soccer.rda': git-lfs: command not found`). I was getting it when I tried to rebase my fork so I deleted my version completely and tried to start from scratch, but I still get it just from cloning the new master branch.

```
git clone https://github.com/thepira/cv.glmmLasso
Cloning into 'cv.glmmLasso'...
remote: Enumerating objects: 284, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 284 (delta 0), reused 3 (delta 0), pack-reused 278
Receiving objects: 100% (284/284), 3.22 MiB | 2.11 MiB/s, done.
Resolving deltas: 100% (138/138), done.
git-lfs smudge 'data/soccer.rda': git-lfs: command not found
error: external filter 'git-lfs smudge %f' failed 127
error: external filter 'git-lfs smudge %f' failed
fatal: data/soccer.rda: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by jaredlander** [comment]
Git lfs is an add on to git and can be downloaded from https://git-lfs.github.com/. It's so that binary files, like the rda file, don't clog up the git repo. Once that is installed you'll be able to pull all the files.

**Comment by jaredlander** [comment]
We are now storing the soccer.rda file with normal git so we don't have to rely on git lfs.
